language: julia
julia:
  - nightly
  - 0.4
os:
  - linux
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("DataArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
